### ISSUE TITLE
Investigate performance issue in iOS

### ISSUE THREAD

**Issue by janicduplessis** [th3rdwave/react-native-safe-area-context#104]
Repro: https://github.com/ahce/rn-safe-area-context-bug

**Comment by ororsatti** [comment]
Ok so I have more info about this, I think.
On an app I'm working on everytime we opened a link on IOS, when returning from it we had this weird layout shift.
After some investigation, I found out that after coming back from a link, I dont get the same width and height.
Take a look at this video:
https://user-images.githubusercontent.com/109456266/225556192-85d3b742-b3a1-48fe-810d-7b6a03f4c86b.mov

As you can see, the `useSafeAreaFrame` returns incorrect values when redirecting back from a link on IOS.

**Comment by ororsatti** [comment]
> The video won’t load but is the issue that the value stays wrong, or that it flashes?
> 
> > Note that insets are not updated synchronously so it might cause a slight delay for example when rotating the screen.

wrong

**Comment by jacobp100** [comment]
Can you provide a minimal repo for that?

**Comment by jacobp100** [comment]
@janicduplessis I looked a little bit into this. I'm pretty convinced it's completely down to React Navigation

Firstly, [they arent' adding a SafeAreaProvider at the top of every screen in the stack](https://github.com/react-navigation/react-navigation/blob/4163cba6b7f9a4bdff1327cde59cea37e6438a59/packages/elements/src/SafeAreaProviderCompat.tsx#L38-L40), so the insets may be incorrect

Also - [they're using the hooks](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.native.tsx#L21-L24), which we know cause flickering

We get so many issues where people assume it's us rather than the library - and we should maybe document that the library has bugs

**Comment by jacobp100** [comment]
I've opened an issue on their repo - https://github.com/react-navigation/react-navigation/issues/11285

I'll close this ticket because I don't think we need to investigate further
