### ISSUE TITLE
Should I use react-native-safe-area-view?

### ISSUE THREAD

**Issue by SrBrahma** [th3rdwave/react-native-safe-area-context#125]
I don't get those two projects. react-native-safe-area-context have a SafeView. react-native-safe-area-view requires react-native-safe-area-context.

Should I use both? Only this one do the job?

**Comment by Ashoat** [comment]
- The `SafeAreaView` in this package is a native implementation since 2.0
- The `SafeAreaView` in `react-native-safe-area-view` has the `forceInset` prop rather than `edges`. `forceInset` is arguably more flexible
- The `SafeAreaView` in this package seems to sometimes have issues when it's first rendered while "clipped" (ie. outside the viewport) (#114)

**Comment by janicduplessis** [comment]
Thanks @Ashoat
