### ISSUE TITLE
Build error on iOS after installing react-native-safe-area-context

### ISSUE THREAD

**Issue by ElChawich** [th3rdwave/react-native-safe-area-context#158]
Getting this error after installing the library for the first time and trying to build the project on xcode. it worked perfectly on android. I'm using RN 0.59.9

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNCSafeAreaProvider", referenced from:
      objc-class-ref in libRNCSafeAreaContext.a(RNCSafeAreaView.o)
  "_OBJC_CLASS_$_RNCSafeAreaShadowView", referenced from:
      objc-class-ref in libRNCSafeAreaContext.a(RNCSafeAreaViewManager.o)
  "_OBJC_CLASS_$_RNCSafeAreaViewLocalData", referenced from:
      objc-class-ref in libRNCSafeAreaContext.a(RNCSafeAreaView.o)
  "_UIEdgeInsetsEqualToEdgeInsetsWithThreshold", referenced from:
      -[RNCSafeAreaView invalidateSafeAreaInsets] in libRNCSafeAreaContext.a(RNCSafeAreaView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by KalAvroniev** [comment]
I'm having same issue. It works fine when using RN 0.63.3 with Pods but not on RN 0.59.10.
Does anyone have a solution? 
I need to use this library to fix an issue and the upgrade to RN 0.63 is not nearly ready yet.

**Comment by ElChawich** [comment]
@KalAvroniev using react-native-safe-area-context@^1.0.0 with react-native-safe-area-view@2.0.0 solved my issue

**Comment by KalAvroniev** [comment]
I tried that but version 1.0.0 of react-native-safe-area-context is very old and does not work the same way as 3.1.9.
Or do you use the SafeAreaView from react-native-safe-area-view@2.0.0? 
Looking at the code react-native-safe-area-context uses react-native-safe-area-view@1.1.1

**Comment by ElChawich** [comment]
true, i use SafeAreaView from react-native-safe-area-view@2.0.0. I only add SafeAreaProvider from react-native-safe-area-context at the root of the app

**Comment by pkuIleaf** [comment]
I found the same error. Any solutions yet. It works without any error in real device

**Comment by dnsmob** [comment]
i bumped from 0.59 to 0.63 and had safe-area-context@3.1.4 so i get a crash too. it turns out that version in particular has a pod dependency on `React`, while it should be `React-Core` (like the latest 3.1.9). if i change the pod directly, some other dependency crashes, and they go on a domino, fix after fix. it turns out a workaround (in my case) is to use the legacy build -- i think there's some sort of parallel build process that causes the new system to break the build. so basically, make sure to have the right version of `context@X.Y.Z` that works with `RN@X.Y.Z`.

personally i dont like manipulating the pod directly, and since this only happens on IDE/debug compilations, i'm going with legacy build until i upgrade all breaking ~shit~ lovely dependencies.

have a look at this issue page, there are plenty of other suggestions that might work.
https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

**Comment by dnsmob** [comment]
bah. it turns out it things have been a bit unstable with other libraries breaking 'randomly' too. i ended adding a step in my pipeline to find and replace any dependency `React` by `React-Core` and it seems to have improved matters.
the command is  
`$ find ./node_modules -name \*.podspec -exec sed -i '' "s/s.dependency.*['\"]React[\"']/s.dependency 'React-Core'/g" {} \;`
HTH

**Comment by SpencerLynn** [comment]
I also ran into this issue. I am on RN 0.59 (still).

I was able to fix it my manually linking off of the files in the `SafeAreaView.xcodeproj` in my main Xcode project. I simply selected every Objective-C file inside the `node_modules/react-native-safe-area-context/ios/SafeAreaView` folder. For some reason it only had two of the files included, when there are many more.

I'm happy to create a pull request if this is a solution desired in the library :D

**Comment by xgenem** [comment]
> I also ran into this issue. I am on RN 0.59 (still).
> 
> I was able to fix it my manually linking off of the files in the `SafeAreaView.xcodeproj` in my main Xcode project. I simply selected every Objective-C file inside the `node_modules/react-native-safe-area-context/ios/SafeAreaView` folder. For some reason it only had two of the files included, when there are many more.
> 
> I'm happy to create a pull request if this is a solution desired in the library :D

Please do!

**Comment by SpencerLynn** [comment]
> > I also ran into this issue. I am on RN 0.59 (still).
> > I was able to fix it my manually linking off of the files in the `SafeAreaView.xcodeproj` in my main Xcode project. I simply selected every Objective-C file inside the `node_modules/react-native-safe-area-context/ios/SafeAreaView` folder. For some reason it only had two of the files included, when there are many more.
> > I'm happy to create a pull request if this is a solution desired in the library :D
> 
> Please do! Thanks a lot!

If I'm able to find some time, I'll definitely open a PR :)
