### ISSUE TITLE
Flicker in the middle of navigation animation

### ISSUE THREAD

**Issue by gunnartorfis** [th3rdwave/react-native-safe-area-context#219]
When navigating to a new screen, a short flicker/jump appears. 
I am using SafeAreaProvider wrapped around the rest of my app and then using SafeAreaView at the root of my screens. 

https://user-images.githubusercontent.com/5333875/138173288-c2dbd192-68eb-40e9-9745-4fab8a529da0.mov

- react-native: 0.66.1
- react-native-safe-area-context: 3.3.2
- @react-navigation/stack 6.0.11
- @react-navigation/native-stack: 6.2.5
- @react-navigation/native: 6.0.6
- iOS: 15, iPhone 13
- macOS 11.6 (Big Sur)
- Macbook Pro 13" M1

**Comment by tommycarpi** [comment]
I managed to fix it by using `useSafeAreaInsets` and `<View>` instead of `<SafeAreaView>`

```
const insets = useSafeAreaInsets();

<View
      style={{
        paddingTop: insets.top,
        paddingBottom: 0,
        paddingLeft: insets.left,
        paddingRight: insets.right
      }}>
</View>
```

**Comment by neiker** [comment]
Seems to be a bug on native implementation only:
https://github.com/th3rdwave/react-native-safe-area-context/blob/main/src/SafeAreaView.native.tsx

Importing web implementation works like expected on native
https://github.com/th3rdwave/react-native-safe-area-context/blob/main/src/SafeAreaView.tsx

**Comment by federicogomezcactus** [comment]
> I managed to fix it by using `useSafeAreaInsets` and `<View>` instead of `<SafeAreaView>`
> 
> ```
> const insets = useSafeAreaInsets();
> 
> <View
>       style={{
>         paddingTop: insets.top,
>         paddingBottom: 0,
>         paddingLeft: insets.left,
>         paddingRight: insets.right
>       }}>
> </View>
> ```

I took the same approach, it works perfectly, just as Safe Area View should by default

**Comment by jamonholmgren** [comment]
@m-sterspace Thanks -- your code fixed a long-standing issue in the new GasBuddy RN app. It'll impact millions. :-)

**Comment by varunvasudeva1** [comment]
@tommycarpi Had this issue for months now and nothing I tried seemed to fix it, except this - thanks a ton!

**Comment by jacobp100** [comment]
This is documented in the readme

**Comment by wouterds** [comment]
Can't we adopt the component by @m-sterspace  into the actual package? Why ship a `SafeAreaView` that doesn't properly work?

**Comment by jacobp100** [comment]
The sage area view component does work. The hooks have a documented delay we can’t work around yet

**Comment by mleister97** [comment]
@jacobp100 I am still facing the flickerin issues in end 2023. The solution of [m-sterspace](https://github.com/m-sterspace) works for me, thank you so much. There is currently no other solution working for me (tested on Android 10)

**Comment by MaratSHU** [comment]
Hi! I catch similar issue on adding autofocus to TextInput on ios (didn't check on android yet). So I prepare two screens and on second screen add <TextInput autofocus/>. On navigating to second screen it cause flickering. Turning off autofocus - works as expected.

**Comment by JClackett** [comment]
Still have this issue, using the hook and apply styles manually stops it

**Comment by badaz** [comment]
I've been struggling with this issue for some months now. What I don't understand is that using SafeAreaView from this lib  used to work built in and without this flicker problem. I've first encountered the problem when migrating to RN 0.72 I think but I can not really assert who is faulty, this lib? react-native? my nav lib (RNN wix)? When reading this issue it seems the problem comes from this lib, however I tried downgrading it, although staying on RN 0.72, but it did not solve the problem for me. So what has changed?

**Comment by gkpo** [comment]
Also still have this issue. I had to use @m-sterspace 's fixed component. Not ideal but will do the trick for now.
Any ideas why this could be happening ? Any fixed planned ?

**Comment by melyux** [comment]
Can you reopen this @jacobp100?

**Comment by Ryguy10712** [comment]
Yes, having this issue today too

**Comment by iamvinny** [comment]
Still happening on iOS (26) in 2026.

This is what I ended up implementing, not the cleanest, but it works.

```tsx
import { useTheme } from '@/hooks/use-theme';
import { Keyboard, StyleSheet, View, type ViewProps } from 'react-native';
import { useSafeAreaInsets, type Edge } from 'react-native-safe-area-context';

type Props = ViewProps & { edges?: Edge[] };

export default function ThemedSafeAreaView({ style, children, edges = ['top', 'bottom', 'left', 'right'], ...rest }: Props) {
    const background = useTheme().background;

    // Insets via the hook, not the native <SafeAreaView>: context has correct
    // values from launch, so lazily-mounted tab screens pad correctly in their
    // first frame instead of jumping when the native view attaches.
    // https://github.com/th3rdwave/react-native-safe-area-context/issues/219
    const insets = useSafeAreaInsets();

    const padding = {
        paddingTop: edges.includes('top') ? insets.top : 0,
        paddingBottom: edges.includes('bottom') ? insets.bottom : 0,
        paddingLeft: edges.includes('left') ? insets.left : 0,
        paddingRight: edges.includes('right') ? insets.right : 0,
    };

    return (
        <View
            style={[styles.container, padding, { backgroundColor: background }, style]}
            onStartShouldSetResponder={() => { Keyboard.dismiss(); return false; }}
            {...rest}
        >
            {children}
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1 },
});
```

**Comment by Ryguy10712** [comment]
It seems that SafeAreaView has been deprecated in favor of the implementation in "react-native-safe-area-context". This method works just fine for me, and the migration isn't crazy when wrapped in a component.

**Comment by iamvinny** [comment]
Just to clarify for anyone landing here: the deprecated SafeAreaView is React Native core's built-in component, [docs](https://reactnative.dev/docs/0.81/safeareaview) and its deprecation notice points to **react-native-safe-area-context** as the replacement. The SafeAreaView this issue tracks (the one exported by react-native-safe-area-context) isn't deprecated; it's the successor. So the migration you describe is core → this library, which is a step before the problem this issue is about.

That said, a current data point: the flicker still reproduces on react-native-safe-area-context 5.7.0 with RN 0.86 (new architecture). 

Repro conditions in my app: a screen that mounts lazily after launch — a tab first visited via expo-router's native tabs — renders its first frame with zero top inset, then jumps down once the native view applies its padding. iOS only in my case; Android was clean. Since the native implementation resolves padding at view-attach time, the first committed frame misses it — screens mounted at launch never show it, which is probably why it works fine in many setups.

The useSafeAreaInsets + plain View workaround I posted earlier in this thread still fixes it completely: the provider has correct values in JS context from launch, so even a lazily-mounted screen pads correctly in its very first frame. Wrapped in a small drop-in component with an edges prop, the migration from SafeAreaView is a one-file change.

**Comment by Ryguy10712** [comment]
Yes, thank you for the clarification. This is what I mean.
