### ISSUE TITLE
useSafeAreaInsets returning 0 on android 12 tablet with app bar.

### ISSUE THREAD

**Issue by agusvazquez** [th3rdwave/react-native-safe-area-context#393]
Hello guys!

Android 12 introduced a taskbar where you can see some of other apps on your device. Attaching an example of the bar on the phone app from the simulator.
https://developer.android.com/about/versions/12/12L/summary

![Screenshot_20230606_123626](https://github.com/th3rdwave/react-native-safe-area-context/assets/1704434/ec4072c0-2187-435d-81a7-90ffe7abc13e)

The problem is, when doing 

```
import {useSafeAreaInsets} from 'react-native-safe-area-context';
...
const insets = useSafeAreaInsets();
console.log(insets);
```

I get 
`{"bottom": 0, "left": 0, "right": 0, "top": 0}`
and it should have insets on both bottom and top, right?

I am initializing the Router (react navigation) wrapped in `<SafeAreaProvider>`. It works fine everywhere else, but not on this particular case.
Currently testing on Android Simulator Nexus 10 API 33

Is android 12 taskbar supported? are there any plans of supporting it?

Thank you very much :)

**Comment by jacobp100** [comment]
I think a stock RN app needs configure changes to extend into the safe areas - and only when it extends into those areas will you see non-zero values

We have a ticket somewhere for the documentation for that, but it’s not been done yet

However, this sounds like a new feature. I’m not sure what the expected behaviour should be. If you play around with it and find some answers, it would be good to hear any outcomes

**Comment by agusvazquez** [comment]
Thanks @jacobp100 for your response. Will try to gather some more info. If you have something specific you guys need please let me know so I can provide that.

**Comment by jacobp100** [comment]
I’ll be honest - it’s been so long since I targeted android I’ve really forgotten how it all works 😅 I definitely xml remember configs though

**Comment by agusvazquez** [comment]
Hello! This was my bad! I had another error on my project. Apologies
